# Copyright 2025 The ChapaUY Authors
# SPDX-License-Identifier: Apache-2.0

steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        echo "Verifying identity and registry access..."
        echo "Account: $(gcloud config get-value account)"
        gcloud artifacts repositories describe prod --project=$PROJECT_ID --location=us-east4 > /dev/null
        gcloud auth print-access-token > token
        TOKEN=$(cat token)
        echo "Token generated: ${TOKEN:0:5}...${TOKEN: -5} (Length: ${#TOKEN})"

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        curl -L https://dl.dagger.io/dagger/install.sh | sh
        export GCP_ACCESS_TOKEN=$(cat token | tr -d '\n')

        # Debug Token Info
        echo "Debugging Token Scopes..."
        curl -s "https://www.googleapis.com/oauth2/v1/tokeninfo?access_token=$$GCP_ACCESS_TOKEN" || echo "Failed to fetch token info"

        # Debug Docker Login
        echo "Testing Docker Login..."
        echo $$GCP_ACCESS_TOKEN | docker login -u oauth2accesstoken --password-stdin us-east4-docker.pkg.dev
        docker pull us-east4-docker.pkg.dev/chapauy-20251216/prod/data:latest || echo "❌ Manual Docker Pull Failed"

        # 1. Build CLI and Web
        echo "Building Web+Data..."
        ./bin/dagger call build-and-publish --token=env:GCP_ACCESS_TOKEN -vvv

        # 2. Build Web+Data
        echo "Building Web+Data..."
        ./bin/dagger call build-web-data --token=env:GCP_ACCESS_TOKEN

        # 3. Deploy Service
        echo "Deploying Cloud Run Service..."
        ./bin/dagger call deploy --token=env:GCP_ACCESS_TOKEN
    env:
      - 'PROJECT_ID=$PROJECT_ID'
      - 'REGION=${_REGION}'
      - 'SHORT_SHA=$SHORT_SHA'
      - 'DAGGER_NO_NAG=1'
options:
    logging: CLOUD_LOGGING_ONLY
